  - name: Load variables from vault
    include_vars: "{{ vault_file }}"
    when: (vault_file is defined) and (vault_file|length > 0)
    no_log: true

  - name: Get all VMs of cluster
    vmware_cluster_vms_info:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      cluster_name: '{{ cluster_name }}'
      validate_certs: false
    delegate_to: localhost
    register: cluster_info

